[package]
name = "rust_project"
version = "0.1.0"
edition = "2024"

[dependencies]
#ferris-says = "0.3.1"
csv = "1.4.0"
rand="0.10.0"
trpl = "0.3.0"
serde = { version = "1.0.228",features = ["derive"] }
serde_json = "1.0.149"
base64 = "0.22.1"
reqwest = { version = "0.13.1", features = ["blocking", "json", "query"] }
tokio = { version = "1.49.0",features = ["macros"] }
futures = "0.3.31"
thiserror = "2.0.18"
actix-rt = "2.11.0"
awc = "3.8.1"
toml = "1.0.6"
serde_yaml = "0.9.34"
calamine = "0.34.0"
indexmap = "2.13.0"
rust_decimal = "1.40.0"
rust_decimal_macros = "1.40.0"
chrono = { version = "0.4.44",features = ["serde"] }



#[profile.release]
#panic = "abort"